<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Portal to Outer Space</title>
<style>
html, body {
  margin: 0;
  padding: 0;
  overflow: hidden;
  height: 100%;
  background: #000;
  font-family: sans-serif;
}

/* Portal Frame */
.portal {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 80vmin;
  height: 80vmin;
  transform: translate(-50%, -50%);
  border-radius: 50%;
  overflow: hidden;
  box-shadow: 0 0 60px 20px rgba(0, 200, 255, 0.6), inset 0 0 80px rgba(0, 255, 255, 0.4);
  background: radial-gradient(circle at center, rgba(0,0,0,0.8) 40%, rgba(0,0,0,1) 100%);
}

/* Space Layers */
.space {
  absolute;
  width: 200%;
  height: 200%;
  top: -50%;
  left: -50%;
  transform-style: preserve-3d;
  perspective: 1000px;
}

/* Stars */
.stars {
  position: absolute;
  width: 100%;
  height: 100%;
  background: transparent;
  z-index: 1;
}
.stars::before, .stars::after {
  content: '';
  position: absolute;
  width: 100%;
  height: 100%;
  background-image: radial-gradient(white 1px, transparent 1px);
  background-size: 3px 3px;
  animation: drift 60s linear infinite;
}
.stars::after {
  background-size: 2px 2px;
  opacity: 0.6;
  animation-duration: 90s;
}

/* Nebula Clouds */
.nebula {
  position: absolute;
  width: 150%;
  height: 150%;
  top: -25%;
  left: -25%;
  background: radial-gradient(circle at 30% 30%, rgba(0,255,255,0.2), transparent 70%),
              radial-gradient(circle at 70% 70%, rgba(255,0,255,0.2), transparent 70%);
  filter: blur(80px);
  z-index: 20;
  animation: swirl 120s infinite linear;
}

/* Back Wall */
.back-wall {
  position: absolute;
  width: 40%;
  height: 40%;
  top: 30%;
  left: 30%;
  background: linear-gradient(135deg, #0ff, #f0f, #00f);
  opacity: 0.3;
  transform: translateZ(-800px);
  z-index: 80;
  border-radius: 20px;
  box-shadow: 0 0 100px rgba(255,255,255,0.2);
}

/* Particles */
.particle {
  position: absolute;
  width: 6px;
  height: 6px;
  background: white;
  border-radius: 50%;
  box-shadow: 0 0 10px #0ff, 0 0 20px #f0f;
  animation: float 10s infinite ease-in-out;
}

/* Animations */
@keyframes drift {
  from { transform: translate(0,0); }
  to { transform: translate(100px, 100px); }
}
@keyframes swirl {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
@keyframes float {
  0%,100% { transform: translateY(0) scale(1); }
  50% { transform: translateY(-20px) scale(1.3); }
}
</style>
</head>
<body>
<div class="portal">
  <div class="space" id="space">
    <div class="stars"></div>
    <div class="nebula"></div>
    <div class="back-wall"></div>
    <!-- Particles generated by JS -->
  </div>
</div>

<script>
// Generate random particles
const space = document.getElementById('space');
for (let i = 0; i < 50; i++) {
  const p = document.createElement('div');
  p.className = 'particle';
  p.style.top = Math.random() * 100 + '%';
  p.style.left = Math.random() * 100 + '%';
  p.style.animationDelay = (Math.random() * 10) + 's';
  space.appendChild(p);
}

// Parallax effect
document.addEventListener('mousemove', e => {
  const x = (e.clientX / window.innerWidth - 0.5) * 40;
  const y = (e.clientY / window.innerHeight - 0.5) * 40;
  space.style.transform = `rotateY(${x}deg) rotateX(${y}deg)`;
});
</script>
</body>
</html>
